### ISSUE TITLE
sendReplyMessage to sender instance

### ISSUE THREAD

**Issue by mindesik** [pnxtech/hydra#220]
Is this possible to send reply to sender node (if have multiple instances running)?

**Comment by cjus** [comment]
@mindesik yes you only need to prefix with the sender hydra.instanceID.  Let me know if the information on the following page isn't helpful: https://www.hydramicroservice.com/docs/hydra-core/messaging.html

**Comment by mindesik** [comment]
@cjus thanks, but how to use this with sendReplyMessage?
